-- SYMBIOSIS DATABASE SETUP
-- Paste this whole file into Supabase SQL Editor and run it.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) between 2 and 24),
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists messages_created_at_idx on public.messages(created_at);
create index if not exists messages_user_id_idx on public.messages(user_id);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

-- Profiles: everyone signed in can read profiles, but only a user can create/update their own.
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Messages: signed-in users can read everything in the public lobby,
-- but can only create/delete their own messages.
drop policy if exists "messages_select_authenticated" on public.messages;
create policy "messages_select_authenticated"
on public.messages for select
to authenticated
using (true);

drop policy if exists "messages_insert_own" on public.messages;
create policy "messages_insert_own"
on public.messages for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "messages_delete_own" on public.messages;
create policy "messages_delete_own"
on public.messages for delete
to authenticated
using (auth.uid() = user_id);

-- Let the browser client query these tables through Supabase's Data API.
grant select, insert, update on public.profiles to authenticated;
grant select, insert, delete on public.messages to authenticated;

-- Enable realtime delivery for new messages.
alter publication supabase_realtime add table public.messages;
