-- Symbiosis PR #2 expansion. Run once in Supabase SQL Editor.

alter table public.profiles add column if not exists profile_layout text not null default 'classic';
alter table public.profiles add column if not exists cursor_style text not null default 'classic_green';
alter table public.profiles drop constraint if exists profiles_profile_layout_check;
alter table public.profiles add constraint profiles_profile_layout_check check (profile_layout in ('classic','split','compact'));
alter table public.profiles drop constraint if exists profiles_cursor_style_check;
alter table public.profiles add constraint profiles_cursor_style_check check (cursor_style in ('classic_green','outline_green','pixel_green'));

alter table public.rooms add column if not exists banner_url text not null default '';
alter table public.rooms add column if not exists category text not null default 'general';
alter table public.rooms add column if not exists pinned_notice text not null default '';
alter table public.rooms drop constraint if exists rooms_banner_url_check;
alter table public.rooms add constraint rooms_banner_url_check check (char_length(banner_url)<=1000 and (banner_url='' or banner_url ~* '^https://'));
alter table public.rooms drop constraint if exists rooms_category_check;
alter table public.rooms add constraint rooms_category_check check (category in ('general','social','gaming','media','fandom','other'));
alter table public.rooms drop constraint if exists rooms_pinned_notice_check;
alter table public.rooms add constraint rooms_pinned_notice_check check (char_length(pinned_notice)<=500);
update public.rooms set category='media' where slug in ('random','nostalgia');

create table if not exists public.room_favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  room_slug text not null references public.rooms(slug) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,room_slug)
);
alter table public.room_favorites enable row level security;
drop policy if exists "room_favorites_own" on public.room_favorites;
create policy "room_favorites_own" on public.room_favorites for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
grant select,insert,delete on public.room_favorites to authenticated;

create table if not exists public.login_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  logged_in_at timestamptz not null default now(),
  device_label text not null default '' check(char_length(device_label)<=120),
  user_agent text not null default '' check(char_length(user_agent)<=500)
);
alter table public.login_history enable row level security;
drop policy if exists "login_history_own_read" on public.login_history;
drop policy if exists "login_history_own_insert" on public.login_history;
create policy "login_history_own_read" on public.login_history for select to authenticated using(auth.uid()=user_id);
create policy "login_history_own_insert" on public.login_history for insert to authenticated with check(auth.uid()=user_id);
grant select,insert on public.login_history to authenticated;

create or replace function public.trim_login_history()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  delete from login_history where user_id=new.user_id and id not in
    (select id from login_history where user_id=new.user_id order by logged_in_at desc limit 50);
  return new;
end;$$;
drop trigger if exists trim_login_history_trigger on public.login_history;
create trigger trim_login_history_trigger after insert on public.login_history for each row execute function public.trim_login_history();

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  title text not null check(char_length(trim(title)) between 1 and 80),
  message text not null check(char_length(trim(message)) between 1 and 240),
  theme text not null check(theme in ('y2k','halloween','winter','anniversary')),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  enabled boolean not null default true,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  check(ends_at>starts_at)
);
alter table public.site_events enable row level security;
drop policy if exists "site_events_read" on public.site_events;
drop policy if exists "site_events_staff_write" on public.site_events;
drop policy if exists "site_events_staff_update" on public.site_events;
drop policy if exists "site_events_staff_delete" on public.site_events;
create policy "site_events_read" on public.site_events for select to authenticated using(true);
create policy "site_events_staff_write" on public.site_events for insert to authenticated with check(public.is_moderator() and auth.uid()=created_by);
create policy "site_events_staff_update" on public.site_events for update to authenticated using(public.is_moderator()) with check(public.is_moderator());
create policy "site_events_staff_delete" on public.site_events for delete to authenticated using(public.is_moderator());
grant select,insert,update,delete on public.site_events to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.export_my_account_data()
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'exported_at',now(),'account_id',auth.uid(),
    'profile',(select to_jsonb(p) from profiles p where p.id=auth.uid()),
    'messages',(select coalesce(jsonb_agg(to_jsonb(m) order by m.created_at),'[]'::jsonb) from messages m where m.user_id=auth.uid()),
    'direct_messages',(select coalesce(jsonb_agg(to_jsonb(d) order by d.created_at),'[]'::jsonb) from direct_messages d where d.sender_id=auth.uid() or d.recipient_id=auth.uid()),
    'friendships',(select coalesce(jsonb_agg(to_jsonb(f)),'[]'::jsonb) from friendships f where f.requester_id=auth.uid() or f.addressee_id=auth.uid()),
    'blocks',(select coalesce(jsonb_agg(to_jsonb(b)),'[]'::jsonb) from blocks b where b.blocker_id=auth.uid()),
    'reports',(select coalesce(jsonb_agg(to_jsonb(r)),'[]'::jsonb) from reports r where r.reporter_id=auth.uid()),
    'owned_rooms',(select coalesce(jsonb_agg(to_jsonb(r)),'[]'::jsonb) from rooms r where r.owner_id=auth.uid()),
    'bulletins',(select coalesce(jsonb_agg(to_jsonb(b)),'[]'::jsonb) from bulletins b where b.author_id=auth.uid()),
    'top_friends',(select coalesce(jsonb_agg(to_jsonb(t)),'[]'::jsonb) from top_friends t where t.user_id=auth.uid()),
    'room_favorites',(select coalesce(jsonb_agg(to_jsonb(f)),'[]'::jsonb) from room_favorites f where f.user_id=auth.uid()),
    'login_history',(select coalesce(jsonb_agg(to_jsonb(l) order by l.logged_in_at desc),'[]'::jsonb) from login_history l where l.user_id=auth.uid()),
    'moderation_actions',(select coalesce(jsonb_agg(to_jsonb(a)),'[]'::jsonb) from moderation_actions a where a.target_user_id=auth.uid()),
    'deleted_messages',(select coalesce(jsonb_agg(to_jsonb(l)),'[]'::jsonb) from message_deletion_logs l where l.author_id=auth.uid())
  );
$$;
revoke all on function public.export_my_account_data() from public;
grant execute on function public.export_my_account_data() to authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='room_favorites') then alter publication supabase_realtime add table public.room_favorites; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='site_events') then alter publication supabase_realtime add table public.site_events; end if;
end $$;
