-- SYMBIOSIS DATABASE SETUP
-- Paste this whole file into Supabase SQL Editor and run it.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) between 2 and 24),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists bio text not null default '' check (char_length(bio) <= 500);
alter table public.profiles add column if not exists location text not null default '' check (char_length(location) <= 80);
alter table public.profiles add column if not exists mood text not null default '' check (char_length(mood) <= 40);
alter table public.profiles add column if not exists avatar_url text not null default '';
alter table public.profiles add column if not exists accent_color text not null default '#39ff14';
alter table public.profiles add column if not exists background_color text not null default '#080b10';
alter table public.profiles add column if not exists frame_style text not null default 'neon' check (frame_style in ('none','neon','double','pixel','fire'));
alter table public.profiles add column if not exists music_url text not null default '';
alter table public.profiles add column if not exists music_title text not null default '' check (char_length(music_title) <= 100);
alter table public.profiles add column if not exists music_track text not null default '' check (music_track in ('','neon-dialup','pixel-hearts','midnight-status','crt-dreams'));
alter table public.profiles add column if not exists player_style text not null default 'terminal';
alter table public.profiles add column if not exists stickers jsonb not null default '[]'::jsonb;
alter table public.profiles drop constraint if exists profiles_player_style_check;
alter table public.profiles add constraint profiles_player_style_check check (player_style in ('terminal','winamp','barebones'));
alter table public.profiles drop constraint if exists profiles_stickers_check;
alter table public.profiles add constraint profiles_stickers_check
check (jsonb_typeof(stickers) = 'array' and jsonb_array_length(stickers) <= 40);
alter table public.profiles add column if not exists role text not null default 'member' check (role in ('member','moderator'));

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.messages add column if not exists room text not null default 'lobby';
alter table public.messages drop constraint if exists messages_room_check;
alter table public.messages add constraint messages_room_check check (room in ('lobby','random','nostalgia'));

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1000),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id)
);

create table if not exists public.lobby_settings (
  id smallint primary key default 1 check (id = 1),
  slow_mode_seconds integer not null default 0,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

alter table public.lobby_settings drop constraint if exists lobby_settings_slow_mode_seconds_check;
alter table public.lobby_settings add constraint lobby_settings_slow_mode_seconds_check
check (slow_mode_seconds >= 0);

create table if not exists public.blocks (
  id bigint generated by default as identity primary key,
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reported_user_id uuid references public.profiles(id) on delete set null,
  message_id bigint references public.messages(id) on delete set null,
  reason text not null check (char_length(trim(reason)) between 3 and 500),
  status text not null default 'open' check (status in ('open','resolved','dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null,
  check (reported_user_id is not null or message_id is not null)
);

insert into public.lobby_settings (id, slow_mode_seconds)
values (1, 0)
on conflict (id) do nothing;

create unique index if not exists friendships_unique_pair_idx
on public.friendships (least(requester_id, addressee_id), greatest(requester_id, addressee_id));

create index if not exists messages_created_at_idx on public.messages(created_at);
create index if not exists messages_user_id_idx on public.messages(user_id);
create index if not exists messages_room_created_at_idx on public.messages(room, created_at desc);
create index if not exists direct_messages_sender_idx on public.direct_messages(sender_id, created_at);
create index if not exists direct_messages_recipient_idx on public.direct_messages(recipient_id, created_at);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.direct_messages enable row level security;
alter table public.friendships enable row level security;
alter table public.lobby_settings enable row level security;
alter table public.blocks enable row level security;
alter table public.reports enable row level security;

-- Role checks run through a security-definer helper to avoid recursive profile RLS.
create or replace function public.is_moderator(check_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = check_user and role = 'moderator'
  );
$$;

revoke all on function public.is_moderator(uuid) from public;
grant execute on function public.is_moderator(uuid) to authenticated;

-- This helper can see both sides of a block while keeping the block list private.
create or replace function public.users_blocked(user_a uuid, user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.blocks
    where (blocker_id = user_a and blocked_id = user_b)
       or (blocker_id = user_b and blocked_id = user_a)
  );
$$;

revoke all on function public.users_blocked(uuid, uuid) from public;
grant execute on function public.users_blocked(uuid, uuid) to authenticated;

-- The UI asks this after every reload/view change. It uses database time and
-- message history, so navigating away cannot reset the visible cooldown.
drop function if exists public.my_lobby_cooldown_remaining();
create or replace function public.my_lobby_cooldown_remaining(check_room text default 'lobby')
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with timing as (
    select
      (select max(created_at) from public.messages where user_id = auth.uid() and room = check_room) as last_at,
      coalesce((select slow_mode_seconds from public.lobby_settings where id = 1), 0) as seconds
  )
  select case
    when public.is_moderator(auth.uid()) or last_at is null or seconds = 0 then 0
    else greatest(0, ceil(extract(epoch from (last_at + make_interval(secs => seconds) - now())))::integer)
  end
  from timing;
$$;

revoke all on function public.my_lobby_cooldown_remaining(text) from public;
grant execute on function public.my_lobby_cooldown_remaining(text) to authenticated;

-- Normal users can edit their profile, but cannot promote themselves.
create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role is distinct from old.role
     and auth.uid() is not null
     and not public.is_moderator(auth.uid()) then
    raise exception 'Only moderators can change account roles';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_role_trigger on public.profiles;
create trigger protect_profile_role_trigger
before update on public.profiles
for each row execute function public.protect_profile_role();

-- Enforce lobby slow mode in the database so it cannot be bypassed in DevTools.
create or replace function public.enforce_lobby_slow_mode()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  wait_seconds integer;
  last_message_at timestamptz;
  remaining integer;
begin
  if public.is_moderator(new.user_id) then
    return new;
  end if;

  select slow_mode_seconds into wait_seconds
  from public.lobby_settings where id = 1;

  if coalesce(wait_seconds, 0) = 0 then
    return new;
  end if;

  select max(created_at) into last_message_at
  from public.messages where user_id = new.user_id and room = new.room;

  if last_message_at is not null and now() < last_message_at + make_interval(secs => wait_seconds) then
    remaining := ceil(extract(epoch from ((last_message_at + make_interval(secs => wait_seconds)) - now())))::integer;
    raise exception 'Slow mode is active. Wait % second(s).', greatest(remaining, 1);
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_lobby_slow_mode_trigger on public.messages;
create trigger enforce_lobby_slow_mode_trigger
before insert on public.messages
for each row execute function public.enforce_lobby_slow_mode();

-- Profiles: everyone signed in can read profiles, but only a user can create/update their own.
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "profiles_update_moderator" on public.profiles;
create policy "profiles_update_moderator"
on public.profiles for update
to authenticated
using (public.is_moderator(auth.uid()))
with check (public.is_moderator(auth.uid()));

-- Everyone signed in sees slow mode; only moderators may change it.
drop policy if exists "lobby_settings_select_authenticated" on public.lobby_settings;
create policy "lobby_settings_select_authenticated"
on public.lobby_settings for select
to authenticated
using (true);

drop policy if exists "lobby_settings_update_moderator" on public.lobby_settings;
create policy "lobby_settings_update_moderator"
on public.lobby_settings for update
to authenticated
using (public.is_moderator(auth.uid()))
with check (public.is_moderator(auth.uid()));

-- Blocks are private to the blocker. Other policies use the table through security-definer helpers.
drop policy if exists "blocks_select_own" on public.blocks;
create policy "blocks_select_own" on public.blocks for select to authenticated
using (auth.uid() = blocker_id);

drop policy if exists "blocks_insert_own" on public.blocks;
create policy "blocks_insert_own" on public.blocks for insert to authenticated
with check (auth.uid() = blocker_id and blocker_id <> blocked_id);

drop policy if exists "blocks_delete_own" on public.blocks;
create policy "blocks_delete_own" on public.blocks for delete to authenticated
using (auth.uid() = blocker_id);

-- Users submit reports; moderators can review the full queue.
drop policy if exists "reports_insert_own" on public.reports;
create policy "reports_insert_own" on public.reports for insert to authenticated
with check (auth.uid() = reporter_id and status = 'open');

drop policy if exists "reports_select_own" on public.reports;
create policy "reports_select_own" on public.reports for select to authenticated
using (auth.uid() = reporter_id or public.is_moderator(auth.uid()));

drop policy if exists "reports_update_moderator" on public.reports;
create policy "reports_update_moderator" on public.reports for update to authenticated
using (public.is_moderator(auth.uid()))
with check (public.is_moderator(auth.uid()));

-- Messages: signed-in users can read everything in the public lobby,
-- but can only create/delete their own messages.
drop policy if exists "messages_select_authenticated" on public.messages;
create policy "messages_select_authenticated"
on public.messages for select
to authenticated
using (true);

drop policy if exists "messages_insert_own" on public.messages;
create policy "messages_insert_own"
on public.messages for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "messages_delete_own" on public.messages;
create policy "messages_delete_own"
on public.messages for delete
to authenticated
using (auth.uid() = user_id or public.is_moderator(auth.uid()));

-- Friendships are visible only to their two participants.
drop policy if exists "friendships_select_participant" on public.friendships;
create policy "friendships_select_participant" on public.friendships for select to authenticated
using (auth.uid() = requester_id or auth.uid() = addressee_id);

drop policy if exists "friendships_insert_requester" on public.friendships;
create policy "friendships_insert_requester" on public.friendships for insert to authenticated
with check (auth.uid() = requester_id and requester_id <> addressee_id and status = 'pending'
  and not public.users_blocked(requester_id, addressee_id));

drop policy if exists "friendships_update_addressee" on public.friendships;
create policy "friendships_update_addressee" on public.friendships for update to authenticated
using (auth.uid() = addressee_id)
with check (auth.uid() = addressee_id and status in ('accepted','declined'));

drop policy if exists "friendships_delete_participant" on public.friendships;
create policy "friendships_delete_participant" on public.friendships for delete to authenticated
using (auth.uid() = requester_id or auth.uid() = addressee_id);

-- DMs are private and require an accepted friendship.
drop policy if exists "direct_messages_select_participant" on public.direct_messages;
create policy "direct_messages_select_participant"
on public.direct_messages for select
to authenticated
using ((auth.uid() = sender_id or auth.uid() = recipient_id) and exists (
  select 1 from public.friendships f where f.status = 'accepted'
  and ((f.requester_id = sender_id and f.addressee_id = recipient_id)
    or (f.requester_id = recipient_id and f.addressee_id = sender_id))
) and not public.users_blocked(sender_id, recipient_id));

drop policy if exists "direct_messages_insert_sender" on public.direct_messages;
create policy "direct_messages_insert_sender"
on public.direct_messages for insert
to authenticated
with check (auth.uid() = sender_id and sender_id <> recipient_id and exists (
  select 1 from public.friendships f where f.status = 'accepted'
  and ((f.requester_id = sender_id and f.addressee_id = recipient_id)
    or (f.requester_id = recipient_id and f.addressee_id = sender_id))
) and not public.users_blocked(sender_id, recipient_id));

drop policy if exists "direct_messages_delete_sender" on public.direct_messages;
create policy "direct_messages_delete_sender"
on public.direct_messages for delete
to authenticated
using (auth.uid() = sender_id);

-- Let the browser client query these tables through Supabase's Data API.
grant select, insert, update on public.profiles to authenticated;
grant select, insert, delete on public.messages to authenticated;
grant select, insert, delete on public.direct_messages to authenticated;
grant select, insert, update, delete on public.friendships to authenticated;
grant select, update on public.lobby_settings to authenticated;
grant select, insert, delete on public.blocks to authenticated;
grant select, insert, update on public.reports to authenticated;

-- Public avatar bucket. Users can only write inside their own user-id folder.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('profile-images', 'profile-images', true, 5242880, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public = true, file_size_limit = 5242880,
  allowed_mime_types = array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "profile_images_insert_own" on storage.objects;
create policy "profile_images_insert_own" on storage.objects for insert to authenticated
with check (bucket_id = 'profile-images' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "profile_images_update_own" on storage.objects;
create policy "profile_images_update_own" on storage.objects for update to authenticated
using (bucket_id = 'profile-images' and owner_id = auth.uid()::text)
with check (bucket_id = 'profile-images' and owner_id = auth.uid()::text);
drop policy if exists "profile_images_delete_own" on storage.objects;
create policy "profile_images_delete_own" on storage.objects for delete to authenticated
using (bucket_id = 'profile-images' and owner_id = auth.uid()::text);

-- Public profile-song bucket. Public means profile visitors can play a song;
-- write/delete access remains restricted to the owner's user-id folder.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('profile-music', 'profile-music', true, 20971520,
  array['audio/mpeg','audio/ogg','application/ogg','audio/wav','audio/x-wav','audio/mp4','audio/x-m4a'])
on conflict (id) do update set public = true, file_size_limit = 20971520,
  allowed_mime_types = array['audio/mpeg','audio/ogg','application/ogg','audio/wav','audio/x-wav','audio/mp4','audio/x-m4a'];

drop policy if exists "profile_music_insert_own" on storage.objects;
create policy "profile_music_insert_own" on storage.objects for insert to authenticated
with check (bucket_id = 'profile-music' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "profile_music_update_own" on storage.objects;
create policy "profile_music_update_own" on storage.objects for update to authenticated
using (bucket_id = 'profile-music' and owner_id = auth.uid()::text)
with check (bucket_id = 'profile-music' and owner_id = auth.uid()::text);
drop policy if exists "profile_music_delete_own" on storage.objects;
create policy "profile_music_delete_own" on storage.objects for delete to authenticated
using (bucket_id = 'profile-music' and owner_id = auth.uid()::text);

-- Enable realtime delivery for new messages.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
  ) then alter publication supabase_realtime add table public.messages; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'direct_messages'
  ) then alter publication supabase_realtime add table public.direct_messages; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'friendships'
  ) then alter publication supabase_realtime add table public.friendships; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'lobby_settings'
  ) then alter publication supabase_realtime add table public.lobby_settings; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'blocks'
  ) then alter publication supabase_realtime add table public.blocks; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'reports'
  ) then alter publication supabase_realtime add table public.reports; end if;
end $$;
