import {useState} from 'react';

export default function ModeratorPanel({reports=[],deletionLogs=[],actions=[],events=[],people=[],rooms=[],canManageTags=false,status,chatFramesEnabled,onChatFrames,onReview,onDeleteMessage,onModerate,onRevoke,onUpdateRoom,onUpdateTags,onCreateEvent,onToggleEvent,onDeleteEvent}){
  const [target,setTarget]=useState(''),[type,setType]=useState('timeout'),[room,setRoom]=useState(''),[minutes,setMinutes]=useState(30),[reason,setReason]=useState('');
  const [eventForm,setEventForm]=useState({title:'',message:'',theme:'y2k',starts_at:'',ends_at:''});
  async function apply(event){event.preventDefault();const expires=Number(minutes)>0?new Date(Date.now()+Number(minutes)*60000).toISOString():null;if(await onModerate({target_user_id:target,action_type:type,room_slug:room||null,reason,expires_at:expires}))setReason('')}
  return <section className="panel moderation-panel"><div className="panel-title"><span>★ Moderator control room</span><span>{reports.filter(r=>r.status==='open').length} open</span></div><div className="panel-body">
    <div className="moderator-toggle"><label><input type="checkbox" checked={chatFramesEnabled} onChange={e=>onChatFrames(e.target.checked)}/> Show customized avatar borders inside chats</label></div>
    <h2>Site-wide events</h2><form className="site-event-form" onSubmit={async e=>{e.preventDefault();if(await onCreateEvent({...eventForm,starts_at:new Date(eventForm.starts_at).toISOString(),ends_at:new Date(eventForm.ends_at).toISOString()}))setEventForm({...eventForm,title:'',message:''})}}><input required maxLength="80" placeholder="Event title" value={eventForm.title} onChange={e=>setEventForm({...eventForm,title:e.target.value})}/><input required maxLength="240" placeholder="Site-wide banner message" value={eventForm.message} onChange={e=>setEventForm({...eventForm,message:e.target.value})}/><select value={eventForm.theme} onChange={e=>setEventForm({...eventForm,theme:e.target.value})}><option value="y2k">Y2K</option><option value="halloween">Halloween</option><option value="winter">Winter</option><option value="anniversary">Anniversary</option></select><label>Starts<input required type="datetime-local" value={eventForm.starts_at} onChange={e=>setEventForm({...eventForm,starts_at:e.target.value})}/></label><label>Ends<input required type="datetime-local" value={eventForm.ends_at} onChange={e=>setEventForm({...eventForm,ends_at:e.target.value})}/></label><button className="neon-button">Schedule event</button></form><div className="site-event-list">{events.map(event=><article key={event.id}><b>{event.title}</b><span>{new Date(event.starts_at).toLocaleString()} → {new Date(event.ends_at).toLocaleString()}</span><button className="tiny-tool" onClick={()=>onToggleEvent(event.id,!event.enabled)}>{event.enabled?'disable':'enable'}</button><button className="tiny-tool danger" onClick={()=>onDeleteEvent(event.id)}>delete</button></article>)}</div>
    {canManageTags&&<><h2>Account tags</h2><div className="tag-manager">{people.map(person=><article key={person.id}><b>{person.username}</b>{['OWNER','CO-OWNER','DEVELOPER','MOD'].map(tag=><label key={tag}><input type="checkbox" checked={(person.tags||[]).includes(tag)} onChange={e=>onUpdateTags(person.id,e.target.checked?[...(person.tags||[]),tag]:(person.tags||[]).filter(value=>value!==tag))}/>{tag}</label>)}</article>)}</div></>}
    <h2>Chat locks</h2><div className="room-lock-grid">{rooms.map(item=><label key={item.slug}>#{item.slug}<select value={item.minimum_role} onChange={e=>onUpdateRoom(item.slug,{minimum_role:e.target.value})}><option value="everyone">Everyone</option><option value="moderator">Moderator+</option><option value="co_owner">Co-owner+</option><option value="owner">Owner only</option></select></label>)}</div>
    <h2>Timeout / kick / mute / ban</h2><form className="moderation-action-form" onSubmit={apply}><select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose user…</option>{people.map(person=><option key={person.id} value={person.id}>{person.username}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="timeout">Timeout</option><option value="kick">Kick</option><option value="mute">Mute</option><option value="ban">Ban</option></select><select value={room} onChange={e=>setRoom(e.target.value)}><option value="">Entire site</option>{rooms.map(item=><option value={item.slug} key={item.slug}>#{item.slug}</option>)}</select><label>Minutes (0 = indefinite)<input type="number" min="0" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><input maxLength="500" placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><button className="neon-button">Apply action</button></form>
    <h2>Active actions</h2>{actions.filter(item=>!item.revoked_at&&(!item.expires_at||new Date(item.expires_at)>new Date())).map(item=><article className="action-row" key={item.id}><b>{item.action_type.toUpperCase()}</b> · {people.find(p=>p.id===item.target_user_id)?.username||item.target_user_id} {item.room_slug&&`in #${item.room_slug}`}<span>{item.reason}</span><button className="tiny-tool" onClick={()=>onRevoke(item.id)}>revoke</button></article>)}
    <h2>Reports</h2>{!reports.length&&<p>No reports yet.</p>}{reports.map(report=><article className={`report-row report-${report.status}`} key={report.id}><div><b>#{report.id} · {report.status}</b><span>{new Date(report.created_at).toLocaleString()}</span></div><p><b>{report.reporter_name}</b> reported <b>{report.reported_name}</b>: {report.reason}</p>{report.message_body&&<blockquote>{report.message_body}</blockquote>}<div className="report-actions">{report.status==='open'&&<><button className="neon-button" onClick={()=>onReview(report.id,'resolved')}>Resolve</button><button className="tiny-tool" onClick={()=>onReview(report.id,'dismissed')}>Dismiss</button></>}{report.message_id&&<button className="tiny-tool danger" onClick={()=>onDeleteMessage(report.message_id)}>Delete message</button>}</div></article>)}
    <h2>Deleted-message archive</h2><p className="archive-note">Self-deletions and staff deletions are permanently recorded here.</p>{deletionLogs.map(log=><article className="deletion-log" key={log.id}><header><b>#{log.message_id} · #{log.room}</b><span>{new Date(log.deleted_at).toLocaleString()}</span></header><p>{log.body}</p>{log.caption&&<small>Caption: {log.caption}</small>}<small>Author: {log.author_id} · Deleted by: {log.deleted_by||'system'}</small></article>)}<div className="moderation-status">{status}</div>
  </div></section>;
}
