import {useState} from 'react';

const CATEGORIES=['general','social','gaming','media','fandom','other'];
export default function RoomsPage({rooms,favorites=[],currentUserId,isStaff,onOpen,onCreate,onUpdate,onFavorite,status}){
  const empty={name:'',slug:'',description:'',category:'general',banner_url:'',pinned_notice:''};
  const [creating,setCreating]=useState(false),[form,setForm]=useState(empty);
  async function create(event){event.preventDefault();if(await onCreate({...form,slug:form.slug.toLowerCase().replace(/[^a-z0-9_-]/g,'')})){setForm(empty);setCreating(false)}}
  function copyRoom(slug){const url=new URL(window.location.href);url.search='';url.searchParams.set('room',slug);navigator.clipboard.writeText(url.toString())}
  const grouped=CATEGORIES.map(category=>[category,rooms.filter(room=>room.category===category)]).filter(([,items])=>items.length);
  return <section className="panel rooms-page"><div className="panel-title"><span># rooms directory</span><button className="tiny-tool" onClick={()=>setCreating(v=>!v)}>+ create public room</button></div><div className="panel-body">
    {creating&&<form className="room-create" onSubmit={create}><label>Room name<input maxLength="48" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>URL name<input maxLength="32" required placeholder="my-room" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(value=><option key={value}>{value}</option>)}</select></label><label>Description<textarea maxLength="300" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Banner image URL<input type="url" maxLength="1000" placeholder="https://..." value={form.banner_url} onChange={e=>setForm({...form,banner_url:e.target.value})}/></label><label>Pinned room notice<textarea maxLength="500" value={form.pinned_notice} onChange={e=>setForm({...form,pinned_notice:e.target.value})}/></label><button className="neon-button">Create room »</button></form>}
    <div className="forum-room-list">{grouped.map(([category,items])=><section className="room-category" key={category}><h2>{category}</h2>{items.sort((a,b)=>Number(favorites.includes(b.slug))-Number(favorites.includes(a.slug))).map(room=><article key={room.slug}>{room.banner_url&&<img className="room-list-banner" src={room.banner_url} alt=""/>}<button className="forum-room-main" onClick={()=>onOpen(room.slug)}><b>#{room.slug}</b><span>{room.description||'No description yet.'}</span><small>{room.is_builtin?'OFFICIAL ROOM':`PUBLIC ROOM · created ${new Date(room.created_at).toLocaleDateString()}`}</small></button><div className="room-list-actions"><button className="room-copy-link" onClick={()=>copyRoom(room.slug)}>copy room link</button><button className="room-copy-link" onClick={()=>onFavorite(room.slug)}>{favorites.includes(room.slug)?'★ unfavorite':'☆ favorite'}</button></div>{(isStaff||room.owner_id===currentUserId)&&<div className="room-owner-controls"><label>Category<select value={room.category} onChange={e=>onUpdate(room.slug,{category:e.target.value})}>{CATEGORIES.map(value=><option key={value}>{value}</option>)}</select></label><label>Slow mode<input type="number" min="0" value={room.slow_mode_seconds} onChange={e=>onUpdate(room.slug,{slow_mode_seconds:Number(e.target.value)})}/></label><label>Media<select value={room.media_mode} onChange={e=>onUpdate(room.slug,{media_mode:e.target.value})}><option value="allowed">Allowed</option><option value="images_only">Images/GIFs only</option><option value="disabled">Disabled</option></select></label><label>Banner URL<input type="url" defaultValue={room.banner_url||''} onBlur={e=>{if(e.target.value!==room.banner_url)onUpdate(room.slug,{banner_url:e.target.value})}} placeholder="Paste, then leave field"/></label><label className="wide-control">Pinned notice<textarea defaultValue={room.pinned_notice||''} maxLength="500" onBlur={e=>{if(e.target.value!==room.pinned_notice)onUpdate(room.slug,{pinned_notice:e.target.value})}}/></label>{isStaff&&<label>Access<select value={room.minimum_role} onChange={e=>onUpdate(room.slug,{minimum_role:e.target.value})}><option value="everyone">Everyone</option><option value="moderator">Moderator+</option><option value="co_owner">Co-owner+</option><option value="owner">Owner only</option></select></label>}</div>}</article>)}</section>)}</div><div className="moderation-status">{status}</div>
  </div></section>;
}
